### ISSUE TITLE
systemctl --user broken.

### ISSUE THREAD

**Issue by dreamss** [hashbang/hashbang#26]
@lrvick @KellerFuchs
To be fair I might of broken it myself trying to get a timer/service to work. `systemctl --user` suddently stopped working on to1 yesterday and to1 today, but the weird part is that it works fine on a different account on to1

```
dreamsss@to1:~$ systemctl --user status test.service -l
â— test.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)

dreamss@to1:~/.config/systemd/user$ systemctl --user status test.service -l
Failed to get D-Bus connection: No such file or directory

dreamss@sf1:~/.config/systemd/user$  systemctl --user
Failed to get D-Bus connection: Connection refused
```

**Comment by KellerFuchs** [comment]
@dreamss Based on what I can currently see running, my guess would be that your logged in at some point where your user systemd instance couldn't start (due to yesterday's `sssd` issue?) and since you still have processes running, your session didn't get properly re-created when connecting back.

If you don't mind, I can run `ansible shell_servers -a 'loginctl terminate-user dreamss'` to close all your sessions, and you can see if your systemd user instance starts properly?
Note that your unit file has syntax issues (because systemd doesn't allow a comment that doesn't start at the beginning of the line) so it won't get started anyhow (unless you fixed it since).

**Comment by dreamss** [comment]
go for it, thanks

**Comment by KellerFuchs** [comment]
@dreamss Done.  Had to do some shell wrangling, as `loginctl` got very confused about the whole situation.

**Comment by daurnimator** [comment]
Ok to close this now?

**Comment by KellerFuchs** [comment]
@daurnimator I guess so.

@dreamss Please reopen this issue if you still encounter the problem.
